#!/usr/bin/env bash
#
# Post (or update) the coverage report as a pull-request comment.
#
# This is best effort: it never fails the build when the token is missing or
# the API call fails, so an unreachable comment cannot break CI.
#
# Environment:
#   COVERAGE_REPORT_FILE  Markdown report written by check-coverage.sh
#   FORGEJO_TOKEN         API token with issue write access
#   PR_NUMBER             Pull request number
#   API_URL               API base URL, e.g. https://forgejo.example/api/v1
#   SERVER_URL            Instance URL, used as a fallback for API_URL
#   RUN_NUMBER/RUN_ID     Workflow run number, used in the footer link
#   REPO                  owner/repository, e.g. shylock/aaau
#
# The comment carries a hidden marker so subsequent runs update the same
# comment instead of piling up new ones.

set -uo pipefail

report_file="${COVERAGE_REPORT_FILE:-coverage-report.md}"
token="${FORGEJO_TOKEN:-}"
pr="${PR_NUMBER:-}"
repo="${REPO:-}"
api="${API_URL:-}"

if [ -z "$api" ] && [ -n "${SERVER_URL:-}" ]; then
  api="${SERVER_URL%/}/api/v1"
fi

log() { printf '%s\n' "$*" >&2; }

if [ ! -f "$report_file" ]; then
  log "Coverage report '$report_file' not found; skipping comment."
  exit 0
fi

if [ -z "$token" ] || [ -z "$pr" ] || [ -z "$api" ] || [ -z "$repo" ]; then
  log "Coverage comment skipped: token, PR number, API URL or repository missing."
  exit 0
fi

if ! command -v jq >/dev/null 2>&1; then
  log "Coverage comment skipped: jq is not installed."
  exit 0
fi

marker="<!-- forge-bot:coverage -->"
run_number="${RUN_NUMBER:-${RUN_ID:-}}"

# Prefer the public repository URL from the event payload over the runner's
# internal server URL, which may point at a non-public address/port.
run_base="${SERVER_URL:-${api%/api/v1}}"
run_base="${run_base%/}/${repo}"
event_path="${GITHUB_EVENT_PATH:-}"
if [ -n "$event_path" ] && [ -f "$event_path" ]; then
  repo_html_url="$(jq -r '.repository.html_url // empty' "$event_path" 2>/dev/null || true)"
  if [ -n "$repo_html_url" ]; then
    run_base="${repo_html_url%/}"
  fi
fi

footer=""
if [ -n "$run_number" ] && [ -n "$run_base" ]; then
  footer="_Generated by \`bisect-ppx-report\` in [workflow run ${run_number}](${run_base}/actions/runs/${run_number})._"
fi

body_file="$(mktemp)"
{
  printf '%s\n' "$marker"
  cat "$report_file"
  if [ -n "$footer" ]; then
    printf '\n%s\n' "$footer"
  fi
} > "$body_file"
payload="$(jq -Rs '{body: .}' < "$body_file")"
rm -f "$body_file"
comments_url="$api/repos/$repo/issues/$pr/comments"

existing="$(
  curl -fsS -H "Authorization: token $token" "$comments_url?limit=100" 2>/dev/null \
    | jq -r --arg marker "$marker" '.[] | select(.body | contains($marker)) | .id' 2>/dev/null \
    | head -n1
)"

if [ -n "$existing" ]; then
  if curl -fsS -X PATCH -H "Authorization: token $token" \
       -H "Content-Type: application/json" -d "$payload" \
       "$api/repos/$repo/issues/comments/$existing" >/dev/null; then
    log "Updated coverage comment $existing."
  else
    log "Failed to update coverage comment $existing."
  fi
else
  if curl -fsS -X POST -H "Authorization: token $token" \
       -H "Content-Type: application/json" -d "$payload" \
       "$comments_url" >/dev/null; then
    log "Posted coverage comment."
  else
    log "Failed to post coverage comment."
  fi
fi

exit 0
